config/routes.rb
SocialThingy::Application.routes.draw do
  resources :users do
    resources :circles, only: [:new, :create, :index]
    resources :posts, only: [:new, :create, :index]
  end

   get "/users/:id/feed", to: "users#feed", as: 'newsfeed'
  resources :circles, only: [:edit, :update, :show, :index, :destroy]
  resources :posts, only: [:edit, :update, :show, :destroy]
  resources :links, only: [:show]
  resource :session

end

app/models/circle.rb
# == Schema Information
#
# Table name: circles
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Circle < ActiveRecord::Base
  validates :user_id, :name, presence: true
  
  belongs_to :user 
  has_many :circle_memberships
  has_many :friends, through: :circle_memberships, source: :friend
end

app/models/circle_membership.rb
# == Schema Information
#
# Table name: circle_memberships
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  circle_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class CircleMembership < ActiveRecord::Base

  belongs_to :friend, class_name: "User", foreign_key: :user_id
  belongs_to :circle
  has_one :owner, through: :circle, source: :user

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  title      :string(255)      not null
#  url        :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Link < ActiveRecord::Base
  validates :post, :title, :url, presence: true

  belongs_to :post, inverse_of: :links
  has_many :shared_circles, through: :post, source: :shared_circles
  has_one :author, through: :post, source: :author

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  author_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :body, :author_id, presence: true

  belongs_to :author, class_name: "User", foreign_key: :author_id, inverse_of: :posts
  has_many :post_shares
  has_many :shared_circles, through: :post_shares, source: :circle
  has_many :links, inverse_of: :post


end

app/models/post_share.rb
# == Schema Information
#
# Table name: post_shares
#
#  id         :integer          not null, primary key
#  circle_id  :integer          not null
#  post_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class PostShare < ActiveRecord::Base
  validates :circle_id, :post_id, presence: true

  belongs_to :circle
  belongs_to :post
  has_one :owner, through: :post, source: :author
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password, :friend

  before_validation :ensure_session_token

  validates :email, :password_digest, :session_token, precence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 2, allow_nil: true }

  has_many :circles
  has_many :circle_memberships, class_name: "CircleMembership", foreign_key: :user_id
  has_many :friends, through: :circles, source: :friends
  has_many :posts, class_name: "Post", foreign_key: :author_id, inverse_of: :author

  def password=(plain_text)
    self.password_digest = BCrypt::Password.create(plain_text)
    @password = plain_text
  end

  def is_password?(password)
     BCrypt::Password.new(password_digest).is_password?(password)
  end

  def self.find_by_credentials(params)
    @user = User.find_by_email(params[:email])
    @user.try(:is_password?, params[:password]) ? @user : nil
  end

  def ensure_session_token
    self.session_token = SecureRandom.hex
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      # @circles = Circle.where(user_id: params[:user_id])
      @circles = @user.circles
    else
      @circles = Circle.all
    end
  end

  def show
    @circle = Circle.find(params[:id])
  end

  def new
    @circle = Circle.new
    @users = User.select{ |user| user.id != current_user.id }
  end

  def create
    @circle = current_user.circles.new(circle_params)

    if @circle.try(:save)
      redirect_to user_circles_url(current_user)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end
  end

  def edit
    @circle = Circle.find(params[:id])
    @users = User.select{ |user| user.id != current_user.id }
  end

  def update
    @circle = Circle.find(params[:id])

    if @circle.update_attributes(circle_params)
      redirect_to user_circles_url(current_user)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end


  end

  private

  def circle_params
    params.require(:circle).permit(:user_id, :name, friend_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = current_user.posts.new

  end

  def create
    @post = current_user.posts.new(post_params)

    @post.links.new(link_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:body, :author_id)
  end

  def link_params
    params.permit(:link => [:title, :url]).require(:link).values
    .reject { |link| link.values.any?(&:blank?) }
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by_credentials(user_params)
    if @current_user
      login!(@current_user)
      redirect_to newsfeed_url(@current_user)
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :json => User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.try(:save)
      login!(@user)
      flash[:notices] = ["User created."]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.try(:update_attributes)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logout
    current_user.ensure_session_token
    current_user.save!
    session[:token] = nil
  end

  def login!(user)
    session[:token] = user.session_token
    @current_user = user
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def auth_token_helper
    "<input type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'
    ".html_safe
  end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/edit.html.erb
<form action="<%= circle_url %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token_helper %>

    Circle Name:<br>
    <input type="text" name="circle[name]" value="<%= @circle.name %>"><br>
    <input type="hidden" name="circle[friend_ids][]" value="">
    <% @users.each do |user| %>
      <label>
        <input
        type="checkbox"
        name="circle[friend_ids][]"
        value="<%= user.id %><%= "checked" if @circle.friends.include?(user) %>"> 
        <%= user.email %><br>
      </label>
    <% end %>

  <p><input type="submit" value="Update Circle"></p>
</form>

app/views/circles/index.html.erb
<h4><%= "#{@user.email}'s " if @user %>Circles</h4>
<% @circles.each do |circle| %>
  <%= link_to circle.name, circle_url(circle) %><br>
<% end %>

app/views/circles/new.html.erb
<form action="<%= user_circles_url(current_user) %>" method="POST">
<%= auth_token_helper %>

    Circle Name:<br>
    <input type="text" name="circle[name]"><br>

    <% @users.each do |user| %>
      <label>
        <input
        type="checkbox"
        name="circle[friend_ids][]"
        value="<%= user.id %>"> 
        <%= user.email %><br>
      </label>
    <% end %>

  <p><input type="submit" value="Add to Circle"></p>
</form>

app/views/circles/show.html.erb
<% @circle.friends.each do | friend | %>
  <%= friend.email %><br>
<% end %>

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

app/views/layouts/_notices.html.erb
<% if flash[:notices] %>
  <% flash[:notices].each do | notice | %>
    <%= notice %><br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThingy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/notices" %>
<%= render "layouts/errors" %>

<% if logged_in? %>
  <%= "Welcome #{current_user.email}"  %>
  <%= button_to "Logout", session_url, method: :delete %>
<% else %>
  <%= button_to "Login", new_session_url, method: :get %>
<% end %>


<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<form action="<%= user_posts_url(current_user) %>" method="POST">
  <%= auth_token_helper %>
  
  <label>Post Title
    <input type="text" name="post[body]">
  </label>
  <br>

  <% 3.times do |i| %>
    <p>
      <label>Link
        <input type="text" name="link[<%= i %>][title]">
      </label>
      <label>URL
        <input type="text" name="link[<%= i %>][url]">
      </label>
    </p>
  <% end %>

  <p><input type="submit" value="Submit"></p>
</form>

app/views/posts/show.html.erb
<h1><%= @post.body %></h1>
<h1>by <%= @post.author.id %></h1>

<% @post.links.each do |link| %>
  <%= link.title %> -  <%= link.url %><br>
<% end %>

app/views/users/feed.html.erb
<% current_user.friends.each do |friend| %>
  <% friend.posts.each do |post| %>
    <b><%= post.author.email %></b>-<br>
    <%= post.body %><br>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="POST">
  <%= auth_token_helper %>
  <label>Email
    <input type="text" name="user[email]">
  </label>
  <label>Password
    <input type="text" name="user[password]">
  </label>
  <p><input type="submit" value="Sign Up" /></p>
</form>